# Ceci est le nom de la branche que GitHub Pages utilise pour publier votre site
branches:
  main:

# Ceci spécifie que votre site doit être construit à partir du répertoire 'docs'
# et qu'il devrait servir le fichier 'courriel.html' comme page par défaut
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      index.html:
        content: |
          <!DOCTYPE html>
          <html>
            <head>
              <title>Courriel</title>
            </head>
            <body>
              <!-- Modifiez le chemin du fichier pour qu'il corresponde à l'emplacement de votre fichier courriel.html -->
              <iframe src="./src/courriel.html" style="width:100%; height:100%; border:none;"></iframe>
            </body>
          </html>
